### PR TITLE
Fix manylinux wheels

### PR DESCRIPTION
**Pull request by maebert**
Wheels would never actually get used because they're installed into the wrong temporary directory.

### CODE REVIEW

**Comment by Miserlou** [comment]
Thanks for the fix, but I have to request the removal of the preference of manylinux wheels over lambda-packages. Lambda-packages are supposed to include versions of the packages on PyPI that should be smaller and better for Lambda.

Want to write a test for this as well? :)

**Comment by maebert** [comment]
That makes sense - but why do we try wheels first then? We could swap the blocks around, try lambda_packages first, and then a wheel if we don't have a package yet.

**Comment by Miserlou** [comment]
That'd be fine as well. The way it is now they'll be overridden, but we don't have to worry about state as much.

**Comment by maebert** [comment]
Alright, this is updated. However looking at the current test structure, you'd have to refactor A LOT to actually test this behavior - in essence, we'd need smoke tests. I'm working on a PR which does exactly that, but for now this should at least fix wheels.

**Pull request merged**
