### PR TITLE
remove references to zappa.io

### LINKED ISSUE #311: zappa.io should redirect to www.zappa.io
going to zappa.io results in a DNS error.

www.zappa.io works fine.

### LINKED ISSUE #1838: Is the blog relevant?
The latest post on https://blog.zappa.io/ is from 2017.
Yet the URL is prominently displayed both on zappa.io and in the github project title.
It's mixed signals at best.

### LINKED ISSUE #1976: Zappa Websites are not working
I'm unable to access any websites for Zappa.

Both the blog (https://blog.zappa.io/) or the root websites (https://zappa.io/)

### PR DESCRIPTION
**Pull request by jneves**
## Description
Given up on waiting for zappa.io to reappear in the net.

## GitHub Issues
Resolves #1976
Resolves #1838 
Resolves #311

### CODE REVIEW

**Comment by mcrowson** [comment]
The blog entries are all on a separate repo: https://github.com/Miserlou/zappa-blog, maybe we could just move those into a docs folder or something within the project and link to them there

**Comment by MRigal** [comment]
I've also suggested the same, as well as updating the headline, but @jneves just pushed on master... https://github.com/Miserlou/Zappa/commit/818f7de2aee18fb2f85e074207e034240dc9e242

**Comment by jneves** [comment]
@MRigal sorry, that had been by mistake - I'm fine with someone cleaning up the blog posts and adding to the docs, but I don't have the time to keep the blog going and nobody else has volunteered for it yet.

**Comment by miketheman** [comment]
Can someone please remove this link from the repo?
Screenshot 2020-05-23 09 09 53

**Comment by mcrowson** [comment]
It is not maintained within git. Only @Miserlou has access to it. I've requested that it be removed but haven't heard back.

**Pull request merged**
