### PR TITLE
Lambda/API Gateway region us-west-1 now available.  See: https://aws.…

### LINKED ISSUE #667: Region us-west-1 is available, but PyPI Zappa (0.35.2) doesn't include it.
## Context

Lambda/API Gateway region `us-west-1` became available [11/27/2016](https://aws.amazon.com/about-aws/whats-new/2016/11/aws-lambda-available-in-us-west-n-california/), but Zappa 0.35.2 gives warnings saying ```Warning! AWS Lambda may not be available in this AWS Region!
Warning! AWS API Gateway may not be available in this AWS Region!``` when doing a `zappa deploy` to `us-west-1`.  

Adding `us-west-1` to zappa.py: `API_GATEWAY_REGIONS` & `LAMBDA_REGIONS` resolves the issue and allows deployment to `us-west-1`.

PR to follow.

### PR DESCRIPTION
**Pull request by evandrone**
…amazon.com/about-aws/whats-new/2016/11/aws-lambda-available-in-us-west-n-california/

## GitHub Issues

Resolves #667

### CODE REVIEW

**Comment by Miserlou** [comment]
Can you update this PR to include all of the available regions now? I think London has APIGW + Lambda too..

**Comment by evandrone** [comment]
No problem.  Added.

**Comment by Miserlou** [comment]
W00t

**Comment by vaibhavmalushte** [comment]
Hi,

I am getting same error, I am trying to run zappa init from 'ap-south-1' (Mumbai - India) and getting same error.
I have added 'ap-south-1' in LAMBDA_REGIONS & API_GATEWAY_REGIONS array but no luck.

Kindly advise.

Thank you,
Vaibhav

**Pull request merged**
