### PR TITLE
Fix the returned order of events in logs

### PR DESCRIPTION
**Pull request by pjz**
## Description
`zappa tail` can currently show old logs misordered.  This patch:

   1.  sorts the received events
   2. fetches *all* the logs; previous code wasn't dealing with the return of a nextToken

### CODE REVIEW

**Comment by Miserlou** [comment]
Groovy

**Comment by pjz** [comment]
Hate to say it, but I think fixing the nextToken bits might have broken live updates. Can someone test?

**Comment by Miserlou** [comment]
Reverting until confirmed fixed, with test.

Would also appreciate it if you could keep the style as it was rather than using kwargs, which make the code less readable, and please try to use explicit variable names rather than abbreviations (ex 'fle_args')

**Comment by pjz** [comment]
I didn't use them frivolously; replacing them means duplicating the call (and args, etc) to `filter_log_events` literally with some guard code that looks like:
```python
if nextToken:
    response = self.logs_client.filter_log_events(
             logGroupName=log_name,
             logStreamNames=all_names,
             filterPattern=filter_pattern,
             limit=limit,
             nextToken=nextToken
         )
else:
    response = self.logs_client.filter_log_events(
             logGroupName=log_name,
             logStreamNames=all_names,
             filterPattern=filter_pattern,
             limit=limit
         )
```
...which to me is less readable than using kwargs, as well as being more susceptible to future error (a fix that gets put in one call but not the other).  Your call though, I guess.

**Comment by Miserlou** [comment]
Is `logs_client` not smart enough to handle `nextToken=None`? Seems like the entire conditional should be unnecessary

**Comment by pjz** [comment]
It apparently isn't.  Trying got me:
```
ParamValidationError: Parameter validation failed:
Invalid type for parameter nextToken, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
```
I wonder what happens if it gets handed a wrong or empty string?  :thinking:

**Comment by pjz** [comment]
...apparently not allowed. Even [core AWS docs](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html ) say "Length Constraints: Minimum length of 1."

**Pull request merged**
