### PR TITLE
Use ==/!= to compare str, bytes, and int literals

### PR DESCRIPTION
**Pull request by cclauss**
Add more key flake8 tests to the Travis CI run to detect and avoid Python 3.8 SyntaxWarnings:
% __python3.8__
```
>>> 3 is 3
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
>>> 'LambdaConfig' is 'LambdaConfig'
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python a __NameError__ is raised which will halt/crash the script on the user.

### CODE REVIEW

**Comment by jneves** [comment]
@cclauss I can't find a reason related to this PR for the test failure. Can you just rebase to current master just to make sure the tests are passing before I merge? Thank you very much!

**Comment by cclauss** [comment]
This kind of hard-to-find bug is why the SyntaxWarning was put into Python 3.8.

The line that fails Travis tests is the line below the modified line in zappa/core.py.  before this PR, that code was not getting executed because:
```
>>> lc = "Lambda"
>>> lc += "Config"
>>> lc == "LambdaConfig"
True
>>> lc is "LambdaConfig"
False
```

**Comment by jneves** [comment]
@cclauss thanks for the debugging!

**Comment by cclauss** [comment]
I have left the __# noqa__ linter directive with a __TODO__ so that the Travis tests pass and we can land this PR.  Afterwards, it would be great if someone with more knowledge of the codebase can remove the linter directive and fix the code which is expecting a dict but getting a list instead.

Similar to #2049.

**Comment by jneves** [comment]
@cclauss no need, I'm fixing it now, it was just a bug on the tests responses file.

**Comment by jneves** [comment]
@cclauss just waiting for the tests on #2055 to run once then will merge that one and this one

**Pull request merged**
