### PR TITLE
binary support

### PR DESCRIPTION
**Pull request by wobeng**

### CODE REVIEW

**Comment by Miserlou** [comment]
Very exciting, can you remove the print statements please?

**Comment by wobeng** [comment]
Done

**Comment by wobeng** [comment]
just need to add

"binary_support" : true

and make sure you  base64.b64encode data you want to encode

**Comment by Miserlou** [comment]
One of the tests is failing, can you look into it? https://travis-ci.org/Miserlou/Zappa/jobs/200061554

**Comment by mcrowson** [comment]
It looks like the Response object we get back might have a content_encoding setting we could use to dynamically determine if we need to set this. Not sure how it all works, but if it is possible to get this from the app we could avoid the setting and everything outside of the handler.py

Response from App:
https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L447

Response has ResponseDescriptors Mixin with content_encoding
http://werkzeug.pocoo.org/docs/0.11/wrappers/#werkzeug.wrappers.CommonResponseDescriptorsMixin

**Comment by Miserlou** [comment]
I like that kind of thinking to make it more transparent - could we use MIMEtype at the middleware layer?

**Comment by Miserlou** [comment]
Boom baby!

**Comment by mcrowson** [comment]
2 Things:
1. Document this in the README
2. Is this for applications that deliver JUST binary data? If i turn this setting on for a simple flask hello-world app would it break things?

**Comment by Miserlou** [comment]
That's what I was hoping to discover to day. Ideally this support would be on a per-request or per-route basis, but having all-or-nothing is better than nothing-or-nothing for now.

**Comment by wobeng** [comment]
works with Content-type. So simple flask hello-world app should not break

**Comment by mcrowson** [comment]
What are the additional paths added/removed for in the APIGW?

**Comment by wobeng** [comment]
So basically how it works is you have to tell api gateway what to treat as binary files. 

I do that with the add and remove function if binary_support is true or false

The possible options can be something like this: image/* or image/jpeg or */* .  I use */* because different browsers sends different Accepts values

So when you request with Accept image/jpeg and the response content type is image/jpeg, it will serve it as binary.

**Comment by Miserlou** [comment]
We should expand that criteria (or make it user-definable), there are many other non-image binary types we may want to serve, ex `application/pdf`, `audio/wav`, etc.

**Comment by wobeng** [comment]
Those are just examples..I think other binary media should work well

**Comment by wobeng** [comment]
making user-definable will be an issue because remember that apigw determines what to treat as binary depending on accept http value. Different browsers sends different accepts so to make sure it works for all you need the gree

**Comment by wobeng** [comment]
oops, I closed the pull request by mistake

**Comment by Miserlou** [comment]
I get a `{"message": "Internal server error"}` error when using this for normal HTTP endpoints.

**Comment by wobeng** [comment]
the latest push should fix that issue

**Comment by wobeng** [comment]
Any update on this?

**Comment by Miserlou** [comment]
This still doesn't appear to work for either plaintext or binary endpoints.

```
[1487011732947] An error occurred during JSON serialization of response: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
  sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
  chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
  return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

For:

```python
@app.route('/logo.jpg')
def logo():
    """Serves the logo image."""

    with open("logo.jpg", 'rb') as bites:
        return send_file(io.BytesIO(bites.read()),
                         attachment_filename='logo.jpeg',
                         mimetype='image/jpg')
```

**Comment by wobeng** [comment]
remember that if you want to use binary, you have to base 64 encode it. Take a look at https://github.com/wobeng/zappa_resize_image_on_fly/blob/master/app.py#L37

**Comment by Miserlou** [comment]
Surely this should be done at the middleware layer, not the application layer?

This is also doesn't explain why non binary endpoints don't work.

**Comment by Miserlou** [comment]
We had a discussion on Slack about the MIMETYPE checking. Any progress? :D

**Comment by wobeng** [comment]
by tomm you will get a push..promise..:)

**Comment by Miserlou** [comment]
:man_dancing: :man_dancing: :man_dancing:

**Comment by wobeng** [comment]
Updated to auto detect and base64encode it.

Examples:

https://github.com/wobeng/zappa_resize_image_on_fly/blob/master/app.py#L15 --> https://jyhmaij1l4.execute-api.us-east-1.amazonaws.com/dev/world

https://github.com/wobeng/zappa_resize_image_on_fly/blob/master/app.py#L23 -->
https://jyhmaij1l4.execute-api.us-east-1.amazonaws.com/dev/example

https://github.com/wobeng/zappa_resize_image_on_fly/blob/master/app.py#L56 -->
https://jyhmaij1l4.execute-api.us-east-1.amazonaws.com/dev/image/example/200x200.jpg

**Comment by Miserlou** [comment]
Works great!

**Comment by wobeng** [comment]
:man_dancing: :man_dancing: :man_dancing::man_dancing: :man_dancing: :man_dancing::man_dancing: :man_dancing: :man_dancing:

**Comment by Miserlou** [comment]
Thank you for your contribution to Zappa!

**Pull request merged**
