### PR TITLE
fixed s3 event trigger function name

### PR DESCRIPTION
**Pull request by AbsolutOD**
## Description
I changed the funk name to be the <project_name>:<event function>.  And I changed the get_function for AWS_event function to parse the record['s3']['configurationId'] properly.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/473

* changed the get_function_for_aws_event to returen the function part of the
  record['s3']['configurationId']

### CODE REVIEW

**Comment by Miserlou** [comment]
I want to poke @parroyo for additional review of this one since he wrote this code. The primary issue is ensuring that it works for both S3 events and stream events.

**Comment by parroyo** [comment]
Hey @Miserlou I've just checked the Pull Request, and It's fine.
S3 events are sending the 'configurationId' field with the following format:
`{lambda-arn}:{funcion-name}` 
I don't know if I introduced the bug adding the aws function mapping or it was another change. Sorry about that.

I guess we should also change the S3 event in test.py:
` u'Records': [{'s3': {'configurationId': 'test_settings.aws_s3_event'}}],`
to something like:
`u'Records': [{'s3': {'configurationId': 'arn:aws:lambda:::test_settings.aws_s3_event'}}],`

**Comment by AbsolutOD** [comment]
I just wanted to mention that the reason that I didn't do the full lambda ARN is because I was concerned about field max size.  I was talking with a peer and he warned me about the size of the Event's Name field on a S3 bucket.

I couldn't find any docs on the actual limit of that field, but I think we could hit the limit if we did the whole <lambda_arn>:<module>.<function>.  So, my thought was to just keep it to the actually lambda function name and the event call function.

**Comment by Miserlou** [comment]
Just tested, works great.

**Pull request merged**
