### PR TITLE
Pip10 compatibility

### PR DESCRIPTION
**Pull request by iamjohnnym**
## Description

Zappa fails due to changes in pip==10.0.0.  `pip` changed how they deal with `get_installed_distributions`.  Unfortunately, the changes require usage of `pip._internal`, which goes against standard but it definitely works.

We can leverage the new method while also ensuring previous versions work.
```python
try: # for pip >= 10
    from pip._internal.utils.misc import get_installed_distributions
except ImportError: # for pip <= 9.0.3
    from pip import get_installed_distributions
```

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/1478

### CODE REVIEW

**Comment by wobeng** [comment]
@iamjohnnym I think you are missed [module 'pip' has no attribute 'main'](https://github.com/Miserlou/Zappa/blob/a93a24e39ceb6b583886735c0409a0d3d6d74824/zappa/core.py#L406)

they made a refactoring, We can support old and new with

```
try:
    from pip import main as pipmain
except:
    from pip._internal import main as pipmain
```

cc @Miserlou

**Comment by scoates** [comment]
I realize this is going for a quick workaround, but it's going to be super fragile. The pip folks [broke this in 9.0.2](https://github.com/pypa/pip/issues/5081), and they're likely to do it again, without notice, in the 10.x tree.

From [the docs](https://pip.pypa.io/en/stable/user_guide/#using-pip-from-your-program):

> pip is a command line program. While it is implemented in Python, and so is available from your Python code via import pip, you must not use pip's internal APIs in this way.

The correct approach here is to use `subprocess` and shell out to the command line. Unfortunately.

**Comment by iamjohnnym** [comment]
Did they?  I was testing it on 9.0.1 - 10.0.0 and all seemed good and well.  

I figured it would fragile but I was leaning on pinning the version range in the requirements, we'd be able to keep it functional until a better way is created.

I believe we can do this with `pkg_resources` instead of `subprocess`.

I have an idea and when I get a bit of time later today, I'll see about changing that PR to be a bit more elegant.

@wobeng I did miss that, I appreciate you pointing it out.  I'll look into that too.

**Comment by iamjohnnym** [comment]
@wobeng I believe I have solved for the `pip.main()` issue.

@scoates I implemented `pkg_resources.WorkingSet()` in lieu of `pip`.  This should solve for current and future supported versions.

**Comment by iamjohnnym** [comment]
@scoates any thoughts on this or do we need to do something else?

**Comment by scoates** [comment]
I haven't tried it and won't be able to until at least mid-May. We're all kind of busy. /-:

**Comment by iamjohnnym** [comment]
Unfortunate but understandable.  Let me know if/when you need me more about this issue.

Keep on kicking ass fellas.

**Pull request merged**
