### PR TITLE
Migrate to Poetry / pyproject.toml

### PR DESCRIPTION
**Pull request by mbeacom**
## Description

The goal of this PR is to replace the `requirements.txt`, `test_requirements.txt` and `setup.py` with a `pyproject.toml`.

This simplifies installation, building, and publishing of the `zappa` package.  Additionally, `poetry` is used to maintain virtual environments and handle package management.

## References

- [PEP-518](https://www.python.org/dev/peps/pep-0518/)
- [Poetry Github](https://github.com/python-poetry/poetry) / [Poetry Website](https://python-poetry.org/)

## GitHub Issues

#2003 
#1997

### CODE REVIEW

**Comment by jneves** [comment]
Sorry, not going to happen. The reason is that I want a set of dependencies in production to be a subset of the test/dev ones, so the one we release is a tested set and poetry does not give us that. Thanks for your work.

**Comment by mbeacom** [comment]
@jneves What do you mean?  That's the purpose of `dev` versus standard packages with Poetry.  `--no-dev` is equivalent to production only dependencies.
🤷‍♂

**Comment by jneves** [comment]
@mbeacom I know that's what people tell me. I tested it and it didn't come through and I was told it was not a bug.

**Comment by jneves** [comment]
@mbeacom now that I have a minute, the case I tried was prod dependency A depends on package B (no version limitation), dev dependency C depends on B<2. Installation without dev install B==2 and with dev would install B==1 (first issue was with Zappa and tqdm, but I replicated with some other packages).

**Pull request closed without merging**
