### PR TITLE
Support AWS-specific environment variables

### PR DESCRIPTION
**Pull request by longzhi**
## Description
Support AWS-specific environment variables.

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/501

### CODE REVIEW

**Comment by Miserlou** [comment]
Related: https://github.com/Miserlou/Zappa/pull/549

**Comment by Miserlou** [comment]
For both of those, I only want to accept the PR when KMS support is enabled and documented.

**Comment by kvey** [comment]
This appears to be in master

**Comment by Miserlou** [comment]
@kvey - the environment variables in Zappa were built before AWS supported their own environment variables, but they function the same. The only reason to swap would be to support KMS, but this PR doesn't support that.

**Comment by richiverse** [comment]
Nice! Actually needed something like this lately

**Pull request merged**
