### PR TITLE
Improved documentation, as described in issue #1073

### PR DESCRIPTION
**Pull request by alfonsomhc**
## Description
Improved documentation for use of API keys, as described in issue #1073

## GitHub Issues
See issue #1073

### CODE REVIEW

**Comment by alfonsomhc** [comment]
@Miserlou , I have improved the documentation as discussed in #1073 :)

**Comment by Miserlou** [comment]
Looks good, can you change the (for example xxx) - that looks unfinished?

**Comment by alfonsomhc** [comment]
I wasn't sure what to use. Any suggestion? I thought about using
'key_value', would that be better?

**Comment by alfonsomhc** [comment]
@Miserlou , hopefully `key_value` is a better choice...

**Comment by Miserlou** [comment]
Great!

**Pull request merged**
