### PR TITLE
Fix for repeated values on headers

### PR DESCRIPTION
**Pull request by jneves**
## Description

This changes the merge_headers function to just copy the multiValueHeaders and add non-existing entries from headers instead of replicating existing values multiple times.

## GitHub Issues

#1821
#1825

### CODE REVIEW

**Comment by jneves** [comment]
@youcandanch when you can, can you check this? Main issue is that values are getting multiplied (because they come in headers and multi_headers). I changed the logic to just had on multiValueHeaders the ones that aren't already there. An alternative would be to keep them as a set instead of a list until the final `','.join()`. Was there a reason why you always merged the values in?

**Comment by IlyaSukhanov** [comment]
This PR also fixes a related bug where [python3-saml](https://github.com/onelogin/python3-saml) gets confused on host string:
```
[1553099381941] [DEBUG] 2019-03-20T16:29:41.941Z 8f4fab42-7659-4739-9428-3d7de85c541e host found: [example.com, example.com]
...
[1553099382037] [DEBUG] 2019-03-20T16:29:42.37Z 8f4fab42-7659-4739-9428-3d7de85c541e SAML Error reason: The response was received at https://example.com, example.com, example.com/saml/example/assert instead of https://example.com/saml/example/assert
```

**Comment by youcandanch** [comment]
The multi-header logic was from #1675, I just cherry-picked that commit into #1802. This looks totally sound by me.

**Comment by marvoloe** [comment]
Thank you guys. Works for me now.

**Pull request merged**
