### PR TITLE
dependency updates including dateutil

### LINKED ISSUE #2108: ERROR: zappa 0.51.0 has requirement python-dateutil<2.7.0, but you'll have python-dateutil 2.8.1 which is incompatible.
python-dateutil<2.7.0 is an outdated version and many packages require python-dateutil>= 2.7.5.

Please update the version of python-dateutil requirement of Zappa.

* Zappa version used: 0.51.0
* Operating System and Python version: 3.7.7 Mac OS

### PR DESCRIPTION
**Pull request by jneves**
## Description
Several package updates and unlocking of dateutil.

## GitHub Issues
Fixes #2108

### CODE REVIEW

**Comment by jasonrhaas** [comment]
Any chance of getting this merged in and a new release cut?

**Comment by jneves** [comment]
Yup

**Comment by jasonrhaas** [comment]
Thank you!

**Comment by chris-erickson** [comment]
Any chance we can get a release on this?  I'm aware I can link to a commit but this is going to cause failures in `pip` very soon:

```
pip install -r requirements.txt --use-feature=2020-resolver
```

```
ERROR: Cannot install arrow 0.16.0 and zappa 0.51.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    arrow 0.16.0 depends on python-dateutil>=2.7.0
    zappa 0.51.0 depends on python-dateutil<2.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Pull request merged**
