### PR TITLE
Support for layers - extension of #1752

### PR DESCRIPTION
**Pull request by jedestep**
## Description
This PR is based off #1752. My additional commits add support for `zappa update` to ensure that layers aren't removed when updating a function, as well as adding some test cases.

## GitHub Issues
#1716

### CODE REVIEW

**Comment by jackric** [comment]
FYI your new unit test is pointless. It just patches a function, calls the patched function, and asserts the patched function was called with what you called it with. It provides no assurances of the correctness of your new code.

I suggest either removing the pointless test, or writing a test that patches low-level AWS operations with mocks , pass a config with layers in at the high-level, and assert the layers option got passed down to the AWS operations correctly.

**Comment by suriya** [comment]
Worked for me as well. Thank you, this is very helpful.

**Comment by jackric** [comment]
@Miserlou can we get this moving?

**Comment by millarm** [comment]
Included in #2027

**Pull request merged**
