### PR TITLE
Adding Flask app detection encoding

### PR DESCRIPTION
**Pull request by Noah-Wagner**
## Description
Added explicit UTF-8 encoding to the detection of Flask apps.
 

## GitHub Issues
[Issue 825](https://github.com/Miserlou/Zappa/issues/825)

### CODE REVIEW

**Comment by Noah-Wagner** [comment]
Python 2 doesn't have an encoding parameter for open() and this broke that build.

**Comment by mcrowson** [comment]
I think 'utf-8' (not 'utf8') is the default encoding anyhow, so I'm not sure this would fix anything.

**Comment by Noah-Wagner** [comment]
I believe the default encoding on Unix platforms is UTF-8 while a quick test on my Windows machine gives me a default encoding of "cp1252" [Wiki link](https://en.wikipedia.org/wiki/Windows-1252).

So I think we need this to explicitly be a UTF-8 file open/read, but Python 2 doesn't support explicit encodings in this method.

**Comment by Noah-Wagner** [comment]
Also [this](https://docs.python.org/3/library/codecs.html#standard-encodings) table is leading me to believe that 'utf8' is an okay alias for 'utf-8', but you're probably right that the correct encoding name is best practice.

Setting this encoding explicitly on my Windows/Python3 dev machine fixed the issue I was having with 
`zappa init`

**Pull request merged**
