### PR TITLE
Add config for dead letter queue

### PR DESCRIPTION
**Pull request by chuckoy**
## Description
Add config option in `zappa_settings.json` to allow configuration of DLQ when Lambda async call fails thrice.

I've decided to use the dictionary format config that the boto3 client uses instead of `<key>: <ARN>(String)` to be consistent.

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/738 Add an entry in zappa_settings to configure the Dead Letter Queue to which triple failed async invokes are sent to

### CODE REVIEW

**Comment by chuckoy** [comment]
Am I correct in that if the boto3 Lambda client is passed an empty dictionary in `DeadLetterConfig` it will simply ignore it? I assumed so from how `vpc_config` was implemented in the code.

**Comment by chuckoy** [comment]
Why did the coverage for `tests_middleware` decrease? I didn't touch `middleware.py` or `wsgi.py`. I can't imagine having that much of an effect for `test_handler` too.

Should I rebase my default value empty dict to the first commit?

**Comment by Miserlou** [comment]
Awesome stuff!

I wouldn't worry about Coveralls here, it's being really funky lately.

This looks okay, but since it's only a single value in the config dictionary, I'd prefer if we just used `dead_letter_arn` in the settings then built the dictionary ourselves, just to make it more simple to configure and use.

It'd also be great if you could add this setting into the `README.md` documentation, along with a link on how to use this feature, or maybe even a paragraph in the Readme on how to use it.

Think you can do that?

**Comment by chuckoy** [comment]
I've added a paragraph in `docs/advanced.rst` as well as a link to the AWS docs for it.

Is how I'm building the dictionary and passing the argument the right way to do it?

**Comment by chuckoy** [comment]
Currently working on adding automated topic/queue creation

**Comment by chuckoy** [comment]
It's not as trivial as I thought. I'd rather get this merged in and create a different pull request for dlq resource creation.

**Pull request merged**
