### PR TITLE
Preserve symlinks when packaging files into the zip file

### PR DESCRIPTION
**Pull request by timmartin**
## Description
Symlinks in the source directories are created as symlinks in the zip file, rather than deploying multiple copies of the same file.

## GitHub Issues

- #754 Zipfile doesn't preserve symlinks

### CODE REVIEW

**Comment by jneves** [comment]
@timmartin if the symlink is pointing to a file that is not being copied into the lambda by other code, does this work? If so, can you add a specific test for that case?

**Comment by timmartin** [comment]
@jneves Good point, it doesn't cope with that. I patched it, but then I realised that this still doesn't cope with the case of symlinks to absolute paths that are outside the directory being packaged (which won't be broken when the link is tested, but will be broken later on when the zip is extracted).

I'll take another run at this later.

**Comment by timmartin** [comment]
This should now deal with the case of symlinks to files outside the directory. I still need to implement the configuration switch before this can be merged, though.

**Comment by jneves** [comment]
@timmartin any news?

**Comment by timmartin** [comment]
Sorry, I should have commented on my last commit. The most recent commit adds the missing configuration switch, so I think this is ready to merge (or at least, ready to review) now. Feedback welcome, of course.

**Comment by timmartin** [comment]
Is there any chance of getting this merged? I believe it's been ready to merge for 3 months now.

**Comment by timmartin** [comment]
OK, nobody seems to be interested in this, I'll close it.

**Pull request closed without merging**
