### PR TITLE
Feature/event kwargs

### PR DESCRIPTION
**Pull request by mcrowson**
#359

This allows for a dict to be passed to an event. Doing so causes us to lose some of the event arguments passed by CW. Not sure if this loss is acceptable. The following keys are no longer in the event. 

['account', 'region', 'detail', 'version', 'time', 'id']

These are not used by Zappa, and won't break existing events because the function_kwargs argument wouldn't be in the settings file.

### CODE REVIEW

**Comment by Miserlou** [comment]
Time doesn't work like that, that'll just pass the time that the event is scheduled rather than the time of the event itself?

**Comment by mcrowson** [comment]
Yup, good call.

**Comment by Miserlou** [comment]
I'm not sure what to do about this one, to be honest.

Can you describe the use case to me?

The problem I'm seeing is that the benefit of having kwargs at the cost of losing region, version and time information (especially for global deployments, scientific/medical deployments which need log data, etc.), doesn't seem worth the cost. 

Especially because the kwargs would be static anyway, it seems like the better solution would simply be to write a function with those static kwargs already in it, and then use that as the event source. Does that make sense?

**Comment by mcrowson** [comment]
That function solution is what we're implementing now, but it just feels strange. Pre-zappa we had a function that would go and get data from a source and parse/store it. The source was an input to the function. Rewriting this into many functions to accomodate all of the sources didn't feel right.

There may be other calls that we could make to get the region and version. I'm not sure how to handle time though.

**Comment by mcrowson** [comment]
I think we now have everything except for the cloudwatch event id that triggers the rule. One other thing is that the time variable is created by Zappa, not by cloudwatch. As these are only for Scheduled Event CW types I don't see this as being a problem.

**Comment by mcrowson** [comment]
@Miserlou Any more thoughts on this?

**Comment by mcrowson** [comment]
Is there something that could get this through, or is it just too hackish with the way lambda takes arguments currently?

**Comment by mcrowson** [comment]
Not needed with #1091

**Pull request closed without merging**
