### PR TITLE
Exception handling callback

### PR DESCRIPTION
**Pull request by aectann**
Useful e.g. for sending crash reports to Raygun or Sentry, or any other error accounting tool.

### CODE REVIEW

**Comment by collingreen** [comment]
This looks great (haven't tested it yet though)

**Comment by Miserlou** [comment]
Merged, I like this change.

**Comment by Miserlou** [comment]
Please proofread your docs in the future though! :)

**Comment by jayfk** [comment]
I wasn't able to make this work with flask. (if preferred, I can open a new issue)

It looks like flasks call to `log_exception` raises an exception that's catched *somewhere?* and then printed to stdout.

```
[1472050994820] Traceback (most recent call last):
[1472050994820] File "/usr/lib64/python2.7/logging/__init__.py", line 880, in emit
[1472050994821] stream.write(fs % msg)
[1472050994821] File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-9rkaZs/Werkzeug/werkzeug/local.py", line 343, in __getattr__
[1472050994821] AttributeError: 'str' object has no attribute 'write'
[1472050994821] Logged from file app.py, line 1587
```

As I'm not very familiar with the codebase, I had a hard time following how exceptions are handled in detail.

requirements
----
```
zappa # latest, installed from source
flask==0.11.1
```

Settings
-------
```javascript
{
    "dev":{
        "app_function": "app.app", 
        "s3_bucket": "foo",
        "exception_handler": "app.unhandled_exceptions"
    }
}
```

Minimal flask app (app.py)
-----
```python
from flask import Flask
from raven import Client

app = Flask(__name__)
SENTRY_DSN = 'https://user:pass@app.getsentry.com/id'


def unhandled_exceptions(e, event, context):
    client = Client(SENTRY_DSN)
    client.captureMessage('In unhandled exceptions')


@app.route('/', methods=['GET'])
def index():
    # this throws an exception
    open("/non-existent.txt")
    return "Hi", 200

# We only need this for local development.
if __name__ == '__main__':
    app.run(debug=True)
```

Full cloudwatch log
-----

```
[1472050994816] [INFO] 	2016-08-24T15:03:14.816Z       	e144417b-6a0b-11e6-89cb-931b5b898cc6    	Detected environment to be AWS Lambda. Using synchronous HTTP transport.
[1472050994820] Traceback (most recent call last):
[1472050994820] File "/usr/lib64/python2.7/logging/__init__.py", line 880, in emit
[1472050994821] stream.write(fs % msg)
[1472050994821] File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-9rkaZs/Werkzeug/werkzeug/local.py", line 343, in __getattr__
[1472050994821] AttributeError: 'str' object has no attribute 'write'
[1472050994821] Logged from file app.py, line 1587
[1472050994821] [ERROR]	2016-08-24T15:03:14.820Z       	e144417b-6a0b-11e6-89cb-931b5b898cc6    	Exception on / [GET]
Traceback (most recent call last):
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1988, in wsgi_app
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1641, in full_dispatch_request
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1544, in handle_user_exception
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1639, in full_dispatch_request
  File "/private/var/folders/82/bhs05x6n72s3bl5xdpm_nzsw0000gn/T/pip-build-I1t8YY/flask/flask/app.py", line 1625, in dispatch_request
  File "/var/task/app.py", line 16, in index
    open("/non-existent.txt")
IOError: [Errno 2] No such file or directory: '/non-existent.txt'
[1472050994822] [INFO] 	2016-08-24T15:03:14.821Z       	e144417b-6a0b-11e6-89cb-931b5b898cc6    	93.232.91.154 - - [24/Aug/2016:15:03:14 +0000] "GET / HTTP/1.1" 500 291 "" "HTTPie/0.9.3" 0/234.269
[1472050994822] {"http_status": 500, "content": "PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMiBGaW5hbC8vRU4iPgo8dGl0bGU+NTAwIEludGVybmFsIFNlcnZlciBFcnJvcjwvdGl0bGU+CjxoMT5JbnRlcm5hbCBTZXJ2ZXIgRXJyb3I8L2gxPgo8cD5UaGUgc2VydmVyIGVuY291bnRlcmVkIGFuIGludGVybmFsIGVycm9yIGFuZCB3YXMgdW5hYmxlIHRvIGNvbXBsZXRlIHlvdXIgcmVxdWVzdC4gIEVpdGhlciB0aGUgc2VydmVyIGlzIG92ZXJsb2FkZWQgb3IgdGhlcmUgaXMgYW4gZXJyb3IgaW4gdGhlIGFwcGxpY2F0aW9uLjwvcD4K"}: LambdaException
Traceback (most recent call last):
  File "/var/task/handler.py", line 396, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 143, in lambda_handler
    raise lex
LambdaException: {"http_status": 500, "content": "PCFET0NUWVBFIEhUTUwgUFVCTElDICItLy9XM0MvL0RURCBIVE1MIDMuMiBGaW5hbC8vRU4iPgo8dGl0bGU+NTAwIEludGVybmFsIFNlcnZlciBFcnJvcjwvdGl0bGU+CjxoMT5JbnRlcm5hbCBTZXJ2ZXIgRXJyb3I8L2gxPgo8cD5UaGUgc2VydmVyIGVuY291bnRlcmVkIGFuIGludGVybmFsIGVycm9yIGFuZCB3YXMgdW5hYmxlIHRvIGNvbXBsZXRlIHlvdXIgcmVxdWVzdC4gIEVpdGhlciB0aGUgc2VydmVyIGlzIG92ZXJsb2FkZWQgb3IgdGhlcmUgaXMgYW4gZXJyb3IgaW4gdGhlIGFwcGxpY2F0aW9uLjwvcD4K"}
[1472051018205] Zappa Event: {u'account': u'747357196988', u'region': u'us-east-1', u'detail': {}, u'detail-type': u'Scheduled Event', u'source': u'aws.events', u'version': u'0', u'time': u'2016-08-24T15:03:10Z', u'id': u'7135a8fb-e8bc-4f80-9a5a-8c5846ba3b7b', u'resources': [u'arn:aws:events:us-east-1:747357196988:rule/test-dev-zappa-keep-warm-handler.keep_warm_callback']}
[1472051018205] Zappa Event: {}
[1472051018205] [DEBUG]	2016-08-24T15:03:38.205Z       	efbca15e-6a0b-11e6-af26-2bf427140012    	Zappa Event: {}
```

**Comment by Miserlou** [comment]
What does "client.captureMessage('In unhandled exceptions')" actually do? You can't write to files in Lambda unless their in tmp.

**Comment by jayfk** [comment]
It basically just sends the string to the Sentry server, defined in `SENTRY_DSN`. That's unrelated, though. That was a quick way to test if it's working. 



> You can't write to files in Lambda unless they're in /tmp.

Yup :D. Calling `open` was an easy way to throw an exception. I can change this to `1/0` :).

**Comment by Miserlou** [comment]
Can you comment on this one please @aectann ?

**Comment by aectann** [comment]
@Miserlou @jayfk The callback is intended for unhandled exceptions. It doesn't catch anything thrown from a wsgi app though, as those are implicitly handled normally (you get a 500 error in the end). On top of that most wsgi app frameworks provide a way to hook into error handling already. E.g. for a flask app that would be something along the lines of:

```
from raven.contrib.flask import Sentry
sentry = Sentry(app, dsn='your dsn')
```

Which normally will give you a better error message in Sentry as it will have access to wsgi request context (the unhandled exception callback only has access to lambda event and context).

So, right now the callback is only useful for things that happen outside of wsgi app (CloudWatch events, zappa command invocations etc). If you think that it should be fired on app exceptions too, it should be fairly easy to do in `handler.py`.

**Comment by Miserlou** [comment]
Ah, perhaps this is a documentation problem then.

**Comment by jayfk** [comment]
@aectann Thanks for the explanation. Makes total sense. I tried the "normal" error handling hook you suggested initially, but it didn't work. Then I saw the part in the docs and gave it a shot.

> Ah, perhaps this is a documentation problem then.

Yup, although exception logging on flask in general seems to be borked right now. I'm going to investigate.

**Pull request merged**
