### PR TITLE
Avoid creating __init__.py in directory with same name as module

### PR DESCRIPTION
**Pull request by marcoesposito1988**
## Description
 

As discussed in #885, if a library contains a folder (e.g. `lib/translations`) in the same folder as a module with the same name (e.g. `lib/translation.py`), creating an `__init__.py` file in it (e.g. `lib/translations/__init__.py`) can break relative imports (e.g. `from .translations import *`).

This patch inserts a check before creating the file to verify if in the parent directory there is a file named in the same way with extension .py or .pyc.

However, this is apparently not enough: the subdirectories should also not contain any init file, otherwise the directory is still considered a namespace package (if I remember correctly the terminology).

So I also modified the check introduced in #769 to look recursively for .py or .pyc files before creating an init file. If a directory does not contain .py or .pyc or any of its subfolders, it will not get the init file.

This seems to solve my issue with Flask-User (now I get another problem with Crypto which seems to be unrelated). Before proceeding with extensive testing, I would welcome any feedback on the approach.

Thanks in advance and also for your awesome job!

## GitHub Issues

Solves #885

### CODE REVIEW

**Comment by Miserlou** [comment]
I'd like to merge this, but it looks like one test related to this change is failing. Can you update the PR to make sure the test is working properly?

**Comment by marcoesposito1988** [comment]
Hi @Miserlou , thanks for the feedback!

Sure, but that will be hard since there are calls to os.path.exist and so on.

What about creating a directory with test data?

**Comment by marcoesposito1988** [comment]
I added the tests with the required test data, and refactored those of `utilities.contains_python_files_or_subdirs()` to use it. I also refactored the flow to avoid scanning a directory twice.

I still have to test this by deploying a package, though.

**Comment by marcoesposito1988** [comment]
So I tried this with a [minimal flask application ](http://flask.pocoo.org/docs/0.12/quickstart/) first, then I added flask-user, and it always worked reliably. I think it is ready for merging.

**Comment by Miserlou** [comment]
And a nice test as well!

**Comment by marcoesposito1988** [comment]
:metal:

**Pull request merged**
