### PR TITLE
Add in the ability to set AWS tags

### PR DESCRIPTION
**Pull request by GregBowyer**
## Description
In concert with #968 this should hopefully allow tags to be created in AWS

## GitHub Issues
#968

---
This change is [Reviewable](https://reviewable.io/reviews/miserlou/zappa/1006)

### CODE REVIEW

**Comment by Miserlou** [comment]
I don't think this will work as intended since you're saying `extra_tags = self.stage_config.get('tags', {})`, not `extra_tags`. I actually like `tags` better, let's just get rid of the `extra` everywhere? Settings `tags` should override the default Zappa tags, not extend.

**Comment by Miserlou** [comment]
Travis doesn't like this. :(

```
Traceback (most recent call last):

  File "/home/travis/build/Miserlou/Zappa/tests/tests.py", line 261, in test_create_api_gateway_routes_with_different_auth_methods

    z.create_stack_template(lambda_arn, 'helloworld', False, False, authorizer)

  File "/home/travis/build/Miserlou/Zappa/zappa/core.py", line 1535, in create_stack_template

    description=description

  File "/home/travis/build/Miserlou/Zappa/zappa/core.py", line 1081, in create_api_gateway_routes

    restapi, lambda_uri, authorizer

  File "/home/travis/build/Miserlou/Zappa/zappa/core.py", line 1133, in create_authorizer

    authorizer_resource = troposphere.apigateway.Authorizer("Authorizer", tags=self.extra_tags)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/troposphere-1.9.4-py2.7.egg/troposphere/__init__.py", line 106, in __init__

    self.__setattr__(k, v)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/troposphere-1.9.4-py2.7.egg/troposphere/__init__.py", line 188, in __setattr__

    (type_name, name))

AttributeError: AWS::ApiGateway::Authorizer object does not support attribute tags
```

Is Tropo behind?

**Comment by Miserlou** [comment]
Change to the code looks good but the README is wrong now, and please put it into alphabetical order. Thanks for your help and patience!

**Comment by zwing99** [comment]
Curiosity, whats the status on this feature?

**Pull request merged**
