### PR TITLE
Feature/support python35

### PR DESCRIPTION
**Pull request by SBillion**
## Description
I did some update to work with python3. It's not finish and I won't have the time to do more before a while, so I would like to share it with you

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/6

### CODE REVIEW

**Comment by Miserlou** [comment]
Damn, this is huge, and I have a feeling that it'll be very relevant in the coming 48h - want to take the final step and make that test pass? Also poking @xuru since I think it's your test :)

**Comment by xuru** [comment]
Hey, sorry, just saw this.  Yeah, I think the problem is in python 3.5, `str` doesn't have a `decode` method.  Looking through the documentation for both 3.5 and 2.7, it looks like we can just add a `b` to the open function.  For example:
```
    with open(egg_link, 'rb') as df:
```
The "binary" mode will have no effect in python 2.7, but will return the string from the `.read` method as a `byte` array which does have a decode method.

The other option, is to do some kind of `if` statement around every file read which would be really ugly.

**Comment by SBillion** [comment]
Yes, problems are around bytes and str, mostly.
I didn't have the time to find a good way to use base64 with python35
An other point of fail is patch_open:

```python
with (patch_open(), mock.patch('glob.glob'), mock.patch( 'zappa.util.copytree')
        ) as ((mock_open, mock_file), mock_glob, mock_copytree):
```

**Comment by Miserlou** [comment]
Closing because we support P36 now! :D

**Pull request closed without merging**
