### PR TITLE
include packages installed with pip install -e ... which end up in src/ virtualenv path

### PR DESCRIPTION
**Pull request by schuyler1d**
## Description
include packages installed with pip install -e ... which end up in src/ virtualenv path

## GitHub Issues
I think this solves at least some issues for https://github.com/Miserlou/Zappa/issues/319

### CODE REVIEW

**Comment by Miserlou** [comment]
This looks like a great solution! Unfortunately the code so far doesn't actually work if there _isn't_ a src directory, so the build is failing. Can you please update the code so that an appropriate check is in place, and that it's tested and covered so that Travis passes without any grumbles?

**Comment by schuyler1d** [comment]
so that fixes the issue.  Can you point me to an example in the code for how to test a virtualenv if you want me to add a test?  I'm not seeing anything obvious in the tests/ directory.

**Comment by Miserlou** [comment]
It'd actually be related to the Travis environment, perhaps you could add a package with a -e to the `test_requirements.txt`? Although that'd only check the code for the positive path, not the negative path. Otherwise, it'll take some more tricky code.

**Comment by Miserlou** [comment]
And I suppose if you want to take that route, adding a lib64 package would increase coverage as well.

**Comment by Miserlou** [comment]
Looks great!

**Pull request merged**
