### PR TITLE
Support for non-LE SSL Certs and non-Route53 DNS providers

### PR DESCRIPTION
**Pull request by bcongdon**
## Description
* Exposes `certificate`, `certificate_key`, and `certificate_chain` in the README documentation. (Should these be renamed to `*_file` for clarity?)
* Adds `using_route53` option. Allows disabling Route53 record changes when doing a `certify`
* Adds a sanity test for the non-Route53 method of certifying

## GitHub Issues
#517 - Adds the ability to bypass the Route53 DNS record updates, allowing both custom certs and DNS
#401 - This functionality already exists, but wasn't exposed anywhere (to my knowledge) in the documentation

### CODE REVIEW

**Comment by Miserlou** [comment]
Oh baby! Hopefully I can get to reviewing this today. 

Suggest we move `using_route53` to `use_route53` to be consistent, or move it to `route53_enabled` to be.. consistent. Requesting input on that one.

**Comment by Miserlou** [comment]
Bumping this one, I'd like to get this merged sometime soon.

**Comment by bcongdon** [comment]
I'm onboard with the config var rename. Changed it to `route53_enabled` to match `apigateway_enabled`

**Comment by Miserlou** [comment]
Let's do it!

**Pull request merged**
