### PR TITLE
Added book reference with title "Building Serverless Python Web Services with Zappa"

### PR DESCRIPTION
**Pull request by abdulwahid24**
## Description
I wrote the book with the title **[Building Serverless Python Web Services with Zappa](https://www.amazon.com/Building-Serverless-Python-Services-Zappa-ebook/dp/B07F2HQFQN)** in association with Packt Publication. This book covers building serverless python web services using Zappa where I have demonstrated with Django, Flask, Bottel and Falcon framework. I covered almost every aspect in association with Zappa where I practically demonstrated Zappa's features. I hope this book will be very useful for anyone who is willing to use Zappa for python application deployment.

I have added book reference under the Zappa Guide section and would request you guys to review and approve this PR.

### CODE REVIEW

**Comment by superappy** [comment]
Hey... great initiative! However, I would suggest a sufficient sample on Amazon. Right now, the sample ends on the "Preface" page of the book. Right now you can only have a look at the table of index in the sample. No one can judge it until you add a chapter or two in the sample.

**Comment by abdulwahid24** [comment]
Hi @superappy,

Thank you for your suggestion. I have updated the link to Book's Github page created by [Packt Publishing](https://github.com/PacktPublishing/Building-Serverless-Python-Web-Services-with-Zappa) as It has detailed information along with sample chapters.

I hope it would suffice to understand the context of the book. Please do let me know in case of any queries.

Thank you.

**Comment by mcrowson** [comment]
Done and thanks for writing this!

**Comment by abdulwahid24** [comment]
Thank you @mcrowson.

**Pull request merged**
