### PR TITLE
Add back rollback functionality

### LINKED ISSUE #2: Add 'Rollback' Capability
It'd be nice if we could do something like

    python manage.py rollback dev 

to return the previously deployed function, or

    python manage.py rollback dev

to rollback 5 versions, etc.

### PR DESCRIPTION
**Pull request by graemeglass**
Resolves #2

I would like to be able to get the FunctionName via the apigateway. Then the user will only have to pass in the stage_name. Any ideas?

### CODE REVIEW

**Comment by Miserlou** [comment]
Is it actually necessary to rollback the API gateway? I thought you could just rollback the Lambda function and have that work? Or are you saying that those are separate functionalities?

**Comment by Miserlou** [comment]
But this is looking good!

**Comment by graemeglass** [comment]
I have never used lambda before, so I am not sure. My assumption was (and could very well be wrong), that you need to update the function, and then redeploy the stage with the updated function. I will investigate this further over the weekend.

**Comment by Miserlou** [comment]
I'm pretty sure that the code and the APIGW are totally separate, and that rolling back the function can be done totally separately from the APIGW. You can check this manually in the console.

**Comment by graemeglass** [comment]
@Miserlou Ah, ok. So in the original issue:

> python manage.py rollback dev 

that dev was the function name, not the stage name? 

If that is the case, then `rollback_lambda_function_version` method is all that is needed to resolve this issue.

**Comment by Miserlou** [comment]
Right, so you set your different production environments in your ZAPPA_SETTINGS, (ex - dev / staging / production), and then rollback would just rollback for the env. Does that make sense?

If you just add one more commit to remove the API GW rollback, I'll merge this in? 

Thanks very much for your contribution!!

**Comment by graemeglass** [comment]
Done. Thanks for the project :-)

**Comment by Miserlou** [comment]
Sweeeet!

Do you want to make a Django management command for this feature as well?

**Comment by graemeglass** [comment]
Will do.

**Pull request merged**
