### PR TITLE
Force fetching pandoc

### PR DESCRIPTION
**Pull request by fifthecho**

### CODE REVIEW

**Comment by gdw2** [comment]
Not working for me.  Don't you need to downlaod pandoc before you try to import it?

```
(env36_64) C:\Users\gwarner\zappa\Zappa>pip install .
Processing c:\users\gwarner\zappa\zappa
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\gwarner\AppData\Local\Temp\pip-3q4ev8qg-build\setup.py", line 7, in <module>
        from pypandoc import convert
    ModuleNotFoundError: No module named 'pypandoc'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gwarner\AppData\Local\Temp\pip-3q4ev8qg-build\setup.py", line 15, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
      File "c:\users\gwarner\zappa\env36_64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 48630: character maps to <undefined>
```

**Comment by fifthecho** [comment]
@gdw2 https://github.com/Miserlou/Zappa/pull/811/files#diff-2eeaed663bd0d25b7e608891384b7298
That should automatically download pandoc when building.

**Comment by gdw2** [comment]
But how do you ensure that the `pypandoc` module is installed before you call `download_pandoc()` (which comes from the `pypandoc` module)?

**Comment by gdw2** [comment]
Should the `requirements.txt` be read and processed before `download_pandoc()`?

**Comment by Miserlou** [comment]
To be honest, I don't think this is the right solution to the problem.

Literally the only reason this requirement is even included is so that when I publish it, the Markdown README looks nice on PyPI, which only supports RST for now.

There is no need to install pypanddoc/pandoc for every single Zappa user, literally only me. I'd rather just figure out what's changed that's causing the exception handler to break.

Thanks for your contribution, but I have to decline this PR.

**Pull request closed without merging**
