### PR TITLE
#776 fix for libmysqlclient.so.18 error when using slim_handler

### PR DESCRIPTION
**Pull request by timj98**
Added include to zappa_settings
Added ctypes to handler to load the selected libraries directly to
PYTHONPATH

## Description
 
This PR fixes the issue where Django using MySQLdb looks for libmysqlclient.so.18 and could not find it in any path when using the slim_handler.  I creates a setting in the zappa_settings file for the specific library to add at handler init. 

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/776

### CODE REVIEW

**Comment by Miserlou** [comment]
Okay, this looks like we're on the right track.

Two things: 

1. Can we include some sane defaults for INCLUDE so that MySQL and others affected by this in lambda-packages all work out of the box?

2. Please change the `print` statements to `print()` so that we don't have to update them when P3 drops.

**Comment by timj98** [comment]
That make sense, I’ll add those tonight.  I will include the defaults for MySQL-Python and mysqlclient.  I was concerned about the coveralls test and resultant reduction in coverage.  

TimJ

**Comment by Miserlou** [comment]
I've merged this in now, thank you for going in on this!

Just as a style point, you included a line of _exceptionally_ ugly code:

```
settings_s += "INCLUDE=[" + ','.join(("'","'")).join(self.stage_config.get('include', [])).join(("'","'")) + "]\n"
```
Since it's already a list, we can simply cast it to a string:

```
include = self.stage_config.get('include', [])
if len(include) >= 1:
    settings_s += "INCLUDE=" = str(include) + '\n'
```
I've gone ahead and changed this already, but in future it's generally good to try to keep the code as short, readable and WTF-free as possible!

Thanks again,
R

**Comment by timj98** [comment]
Thanks.  I appreciate the opportunity and the feedback. 

TimJ

**Pull request merged**
