### PR TITLE
[#1164] Launch django with a different wsgi application

### PR DESCRIPTION
**Pull request by aarcro**
## Description
If both `django_settings` and `app_function` are defined, use the app_function as the wsgi app, but treat it like django.

This will help integrate with random wsgi middleware, (hopefully) NewRelic, and [django-configurations](https://github.com/jazzband/django-configurations)
 

## GitHub Issues

https://github.com/Miserlou/Zappa/issues/1164

### CODE REVIEW

**Comment by aarcro** [comment]
Confirmed today, that New Relic monitoring does work with this in place.

`django_app/wsgi.py`

```python
import logging
import newrelic.agent
import os

# Will collect NEW_RELIC_CONFIG_FILE and NEW_RELIC_ENVIRONMENT from the environment
newrelic.agent.global_settings().enabled = True
if 'NEW_RELIC_CONFIG_FILE' in os.environ:
    print('Starting New Relic agent')
    newrelic.agent.initialize(log_file='stderr', log_level=logging.DEBUG)


from django.core.wsgi import get_wsgi_application  # NOQA

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "webapp.settings")

application = get_wsgi_application()
```

**Comment by davesave** [comment]
merge anytime soon?

**Comment by jxltom** [comment]
I can't make it work with django-configurations using this PR.

Currently, I have run raw command such as ```zappa invoke dev "from configurations.management import execute_from_command_line; execute_from_command_line(['manage.py', 'collectstatic'])" --raw``` to achive functions from ```manage.py```

**Comment by aarcro** [comment]
@jxltom Did you set both `django_settings` and `app_function`? You'll need both.

**Comment by jxltom** [comment]
Oh, I'm so sorry. It works perfect with django-configurations. The last time I failed is because my local develop environment is not updated to using your PR. There is some problem with package management tool pipenv which I'm using.

Thanks, and hope it can be merged soon.

**Comment by mchagas90** [comment]
@aarcro or @matara... how is your config under `app_function`? I'm having problems with this configuration too...

**Pull request merged**
