### PR TITLE
Remove the use of lambda-packages

### PR DESCRIPTION
**Pull request by jneves**
## Description
With the drop of python 2.7, lambda-packages stopped being useful.

### CODE REVIEW

**Comment by mcrowson** [comment]
I like it. Remove from requirements as well?

**Comment by jneves** [comment]
@mcrowson oops, done.

**Comment by havocbane** [comment]
This breaks backward compatibility, which wouldn't be a big deal if the version numbering followed semvar, but since it doesn't it caused us a major headache today.

**Comment by mcrowson** [comment]
How did you fix it?

**Comment by havocbane** [comment]
We pinned to version 0.49.0 at first. That worked short-term, but we didn't want to stay pinned so we then later spent the effort to upgrade and remove lambda-packages and upgrade to 0.51. My point above is more that breaking changes should be a major version increment.

**Comment by daneah** [comment]
Do any folks involved here know how one would best go about pre-compiling `mysqlclient` (on macOS, but for use on Lambda) these days? Hadn't deployed my app in some time and wondering how I might be able to modernize instead of pinning hard on a few things.

**Pull request merged**
