### PR TITLE
Enable Private API GW via EndpointConfiguration

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
## Description
This change makes EndpointConfiguration configurable. This, primarily,
enables for creation of Private API Gateway Endpoints, ones only
accessible from within a VPC. Documentation is updated with example
configuration of the API Gateway and Resource policy.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1540

## See also
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html

### CODE REVIEW

**Comment by glassresistor** [comment]
Any thoughts on this?  I would love to have it merged in soon.

**Comment by monkut** [comment]
Interested in this.. but still trying to figure out how to package our app with surrounding VPC setup/configuration..

**Comment by jneves** [comment]
Looks good to me. Ideally needs someone to test it out for different python versions and report back.

**Comment by IlyaSukhanov** [comment]
FWIW; tested this with 3.6, can test with 2.7 also

**Comment by gpkc** [comment]
I was able to successfully test this on both Python 2.7 and 3.6.

However, I am getting a `ConnectionError` on every `zappa deploy` and `zappa update`. This happens because zappa does a `GET` to the endpoint after the deployment (see the `touch_endpoint` method).

This would not happen, I believe, if two conditions are met:
* You are connected to the VPC, therefore being able to access the private endpoint
* You enable the `Enable Private DNS Name` option when creating the endpoint, which allows you to call the API Gateway URL directly, instead of having to use the endpoint URL (see https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html#apigateway-private-api-test-invoke-url)

**Comment by jneves** [comment]
Merged in #1820 - thanks a lot!

**Pull request closed without merging**
