### PR TITLE
Add Lambda native env vars

### PR DESCRIPTION
**Pull request by geeknam**
## Description
Add AWS Lambda native environment variables

Related to: https://github.com/Miserlou/Zappa/issues/501

### CODE REVIEW

**Comment by Miserlou** [comment]
This looks good, but it doesn't seem connected the the CLI yet - should I expect that in addition this commit?

**Comment by geeknam** [comment]
@Miserlou Zappa settings already includes environment_variables in `stage_config`. I'm getting the config from here: https://github.com/geeknam/Zappa/blob/6136f0548f6b42653f2495e880c7522ca5bd638f/zappa/cli.py#L1436

Not sure if that's what you mean

**Comment by Miserlou** [comment]
Ah, so the problem there is that it's a conflict with the existing environment variables, which should be explicitly separated.

Please move _these_ environment variables to the vendor-prefixed `aws_environment_variables` and update the documentation accordingly.

**Comment by Miserlou** [comment]
Also, the really interesting thing about AWS env vars is the use of KMS. Does this PR address that?

**Comment by jonatasbaldin** [comment]
@Miserlou could we close this since its merged?

**Comment by jneves** [comment]
Already merged.

**Pull request closed without merging**
