### PR TITLE
Use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for async boto Sessions if present

### PR DESCRIPTION
**Pull request by exp0nge**
## Description
 
Use AWS keys for boto Session for async requests.
## GitHub Issues

Miserlou/Zappa/issues/1043

### CODE REVIEW

**Comment by mjschultz** [comment]
`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set for every single Lambda invocation no matter what, so the `else` condition here will never execute in practice. I suspect this is working for you because you are explicitly setting those to variables via environment variables somewhere?

**Comment by exp0nge** [comment]
I'm using the `zappa_settings.json` `environmental_variables` setting. I'm not sure what's going on with the session but this patch lets me use the async calls.

**Comment by mjschultz** [comment]
I put a comment on your issue since I think that discussion is better put over there.

**Comment by exp0nge** [comment]
Check issue for resolution

**Pull request closed without merging**
